### ISSUE TITLE
mobile friendly

### ISSUE THREAD

**Issue by jammin84** [southern-wind/wind#10]
Site isn't mobile friendly at all. Not usable.

**Comment by spinza** [comment]
Have some user commenting on this: 
http://www.ctwug.za.net/showthread.php?6151-WIND-amp-DNS-Moved-Feedback-here-please&p=50287&viewfull=1#post50287

What do you think?

**Comment by jammin84** [comment]
looks like a nice quick fix,  and will be more functional than its current state. :)

**Comment by jammin84** [comment]
Has been made somewhat more usable. closed.
