### ISSUE TITLE
After adding/editing ip address the browser returns to the node info section rather than network section

### ISSUE THREAD

**Issue by spinza** [southern-wind/wind#12]
We've launched our site now.  Live at wind.ctwug.za.net.
Will post a few user niggles as they come up.

This comment probably applies to many of the editing sub-section type pages.

**Comment by jammin84** [comment]
nice one. hope its going well.

**Comment by jammin84** [comment]
the Tabs are JS based and get started from the following code.

```
$('.tabbed').tab();
```

This is the Tab html.

```
<ul class="nav nav-tabs">
        <li class="active"><a href="#tab-info" data-toggle="tab">Node info</a></li>
        <li><a href="#tab-links" data-toggle="tab">Links</a></li>
        <li><a href="#tab-network" data-toggle="tab">Network</a></li>
        <li><a href="#tab-services" data-toggle="tab">Services</a></li>
        <li><a href="#tab-myview" data-toggle="tab">Node's View</a></li>
        <li><a href="#tab-nodesettingschanges" data-toggle="tab">ChangeLog</a></li>
</ul>
```

Reference documentation for how this works.
http://www.w3schools.com/bootstrap/bootstrap_ref_js_tab.asp

**Comment by jammin84** [comment]
The easy fix should be to have the returning page set the relative tab to active.

So if you'd just updated something in the network tab, then the above example will now look like this.

```
<ul class="nav nav-tabs">
        <li><a href="#tab-info" data-toggle="tab">Node info</a></li>
        <li><a href="#tab-links" data-toggle="tab">Links</a></li>
        <li class="active"><a href="#tab-network" data-toggle="tab">Network</a></li>
        <li><a href="#tab-services" data-toggle="tab">Services</a></li>
        <li><a href="#tab-myview" data-toggle="tab">Node's View</a></li>
        <li><a href="#tab-nodesettingschanges" data-toggle="tab">ChangeLog</a></li>
</ul>
```

**Comment by jammin84** [comment]
the relative file is
templates/basic/includes/pages/node_editor/node_editor.tpl

**Comment by jammin84** [comment]
So the success / redirect page code sequence is as follows.

includes/pages/node_editor/node_editor.php 
calls 
globals/classes/message.php

This is the call from node_editor
`$main->message->set_fromlang('info', 'update_success', self_ref());`
Some Background on self_ref (found in globals/functions.php)

```
/**
 * @brief Get a link to the current resource
 * @param array $extra A list of extra query parameters for this link (same will be overrided)
 * @return string The absolute url for this resource.
 */
function self_ref($extra_query = array()) {
        $params = array_merge(get_query_string_array(), $extra_query);
        return make_ref(get_path(), $params);
}
```

Thats all i got time for today. But something along the lines of adding the tab reference in the $extra_query of self_ref should be sufficient.

**Comment by spinza** [comment]
Cool that would take me ages to figure out.  Will see if I can get a volunteer coding.  Otherwise I will implement at some point.

**Comment by jammin84** [comment]
good work @MDE186. 

this has been resolved. closed.
