### ISSUE TITLE
Email entry on user form should be verified as at least appearing to be a valid email address

### ISSUE THREAD

**Issue by spinza** [southern-wind/wind#17]
Currently you can put anything in there it seems.

**Comment by jammin84** [comment]
agreed. Use the inbuilt filter validate. @MDE186 perhaps you'd like to handle this one?

http://www.w3schools.com/php/filter_validate_email.asp

**Comment by MDE186** [comment]
Will have a look :)

**Comment by spinza** [comment]
I've found an instance of two email addresses in that field and also one of a host name instead of an email there.  And those are the better examples.

**Comment by spinza** [comment]
Was closed by #65
