### ISSUE TITLE
No way to add a reverse lookup.

### ISSUE THREAD

**Issue by jammin84** [southern-wind/wind#21]
Reverse lookups are super important when doing trace's and such.
ie doing a lookup on ip a.b.c.d

I've already done this in WAFN and will add the code shortly.

It will appear in the network tab as "Reverse IP addresses"

**Comment by spinza** [comment]
I'm not sure if I'm being daft but isn't the reverse just the inverse of
all A records?

Our A records are taken from ip_addresses.  And our PTR records are taken
from ip_addresses as well?

**Comment by jammin84** [comment]
perfectly valid question. I'd initially thought the same thing myself before being requested to implement it.

A common use is for servers which may host lots of things with websites / mail servers. Say the following all pointed to the same server.
mail.node1.wind
mail.node2.wind
www.node3.wind

with the reverse being something descriptive for diagnosis.
eth2.bigserver.node6.wind

you wouldn't know its real origin or owner is actually node6.wind unless you did a reverse. Also a port or similar is typicaly used in a reverse which can diagnosis (ie a router)

**Comment by spinza** [comment]
I'm not fully following your example but this is how we work:
mail.node1.wind CNAME server.node1.wind (from ip_cname table)
www.node1.wind CNAME server.node1.wind (from ip_cname table)
server.node1.wind A 172.18.1.10  (from ip_addresses)
10.1.18.172... PTR server.node1.wind (from ip_addresses)

This guy is hosting mail and www on server.node1.wind.

If he's hosting the general services for our wug we add a manual cname at top level also.
mail.wind CNAME mail.node1.wind
www.wind CNAME www.node1.wind

**Comment by spinza** [comment]
People who do not know how CNAMEs work often do the following:
they add mail.node1.wind to ip addresses as 172.18.1.10
then also www.node1.wind to ip addresses with same ip
and also server.node1

We then create three PTRs so a reverse lookup gets you one of the above randomly.  Duplicate PTRs do not seem to generate problems with bind/powerdns at least.

**Comment by jammin84** [comment]
re: mail.node1, www.node1 etc:  I was saying the same thing with PTR records for the forward.

I was also saying that just making the reverse name the same as the forward name isn't always applicable. Its typical that a host / router will use a reverse name that is descriptive of a port or hardware that it passes through. -> eth2.bigserver.node6.wind

The true reverse ip should only ever have one reverse record and not a random selection of reverse names.

True, CNAMEs are for linking to another ip, but technically CNAMES aren't meant to be used for MX's either. So, CNAMEs aren't applicable for everything.

**Comment by spinza** [comment]
OK cool.

**Comment by spinza** [comment]
Fair enough on mail mx.  I was just using it as an example.

**Comment by jammin84** [comment]
note: being handled in #58

**Comment by spinza** [comment]
This is closed by #58

**Comment by spinza** [comment]
This is closed by #58
