### ISSUE TITLE
schema-v1.2 cname column definition

### ISSUE THREAD

**Issue by jammin84** [southern-wind/wind#24]
@spinza wanted to query you on /tools/updates/schema-v1.2.inc.php

I believe the unique should be false or removed. otherwise you'll never be able to add more than one cname to a node_id.

$tb->addColumn('node_id', 'int unsigned', array(
                'not_null' => true,
                'default' => '0',
                'unique' => true));

**Comment by spinza** [comment]
Cool will have a look. Will test on wind-dev.

Our production I just copied the existing database and manually upgraded as it was not close to the schema in many places.

**Comment by jammin84** [comment]
cname definition corrected.. closed.
