### ISSUE TITLE
Node subnetwork 

### ISSUE THREAD

**Issue by wacko141za** [southern-wind/wind#26]
Node subnetwork table is not properly aligned

![problemwind2](https://cloud.githubusercontent.com/assets/2084416/12621799/f106eac8-c52a-11e5-866e-3de131543663.PNG)

**Comment by jammin84** [comment]
thanks for the screenshot. I'd never even seen this feature used before :tongue: 

looks to me like it doesn't use the table template.

**Comment by jammin84** [comment]
@wacko141za this has been resolved. closed.
