### ISSUE TITLE
LOS popup

### ISSUE THREAD

**Issue by wacko141za** [southern-wind/wind#27]
When checking LOS between nodes via node view of one node, the resulting popup window is not sized properly and does not update when enlarged to correct size
![problemwind3](https://cloud.githubusercontent.com/assets/2084416/12621870/460cb6d8-c52b-11e5-994b-02003e87bb24.PNG)

**Comment by MDE186** [comment]
@wacko141za what browser you using?

**Comment by wacko141za** [comment]
I have been experiencing this issue on chrome

**Comment by spinza** [comment]
I haven't seen it.

**Comment by jammin84** [comment]
@wacko141za can you please confirm if this is still an issue?

We haven't seen it in the current version.

**Comment by jammin84** [comment]
@wacko141za please re-open if still occuring.

**Comment by spinza** [comment]
I seem to see something similar actually.  But my border is dragable.
![image](https://cloud.githubusercontent.com/assets/3501598/13244502/5c6d00ba-da0f-11e5-8857-4497d7e7821c.png)

**Comment by jammin84** [comment]
mine. chrome. 100% zoom
![image](https://cloud.githubusercontent.com/assets/6802951/13244807/1c49e90a-da44-11e5-9920-af08e770488c.png)

The examples @spinza and @wacko141za has a lot more padding on the left of the plot image.

At a guess this is some kind of css issue. Perhaps font-size em VS px.

**Comment by jammin84** [comment]
Can you both also please check your zoom settings in Chrome when on the wind ctwug tab.

**Comment by spinza** [comment]
Mine is at 100%.

**Comment by spinza** [comment]
Also checked in incognito mode if it might be related to a plugin but get the same.
