### ISSUE TITLE
Formating of Node Links

### ISSUE THREAD

**Issue by wacko141za** [southern-wind/wind#28]
The node links table is not properly aligned, making it unreadable

![problemwind1](https://cloud.githubusercontent.com/assets/2084416/12621893/6a586bea-c52b-11e5-80f4-87a182ae6019.PNG)

**Comment by jammin84** [comment]
fixed for client.

Just realised, not fixed for AP. There seems to be another file for that.

**Comment by MDE186** [comment]
Would it not be this page?

[Here](https://github.com/southern-wind/wind/blob/master/templates/basic/includes/pages/nodes/nodes_view_table_links_ap.tpl)

**Comment by jammin84** [comment]
correct, it was just getting the time to revise n test.

**Comment by jammin84** [comment]
@wacko141za this has been resolved. Closing.

![image](https://cloud.githubusercontent.com/assets/6802951/13238447/fc290ce0-da0d-11e5-8d87-d0a7beba0786.png)
