### ISSUE TITLE
All IP columns in database should be unsigned int(10)

### ISSUE THREAD

**Issue by spinza** [southern-wind/wind#41]
The pre 1.1 sql has a bunch of issues in this regard.

**Comment by spinza** [comment]
Table / Columns with the issue:
areas: ip_start/ip_end
dns_nameservers: ip
ip_addresses: ip
ip_ranges: ip_start/ip_end
regions: ip_start/ip_end
subnets: ip_start/ip_end

**Comment by spinza** [comment]
I suspect the error only manifests when entering IPs >128.0.0.0 which is why some haven't spotted it yet.  We use 172.18 and 172.26 and other wireless nets in SA use other parts of 172.

**Comment by MDE186** [comment]
Hey, I updated my database with your changes but cannot add IP information under subnet.

I.e. if I enter 172.18.221.1 - 172.18.221.5 > it shows - 0.0.0.0 0.0.0.0

**Comment by spinza** [comment]
Try on  https://wind-dev.ctwug.za.net/

I'm pretty sure me and @wacko141za tested it and it was working there.

**Comment by MDE186** [comment]
Get a database error when trying to access node edit page.

[image: Inline image 1]

**Comment by spinza** [comment]
Ah that fix is not merged yet...  Sorry.

**Comment by MDE186** [comment]
Cool. Give me a heads up when you ready.

**Comment by spinza** [comment]
Updated wind-dev to include the fix and its working: https://wind-dev.ctwug.za.net/index.php/nodes?node=1
So this error is closed by the PR #42
