### ISSUE TITLE
Regression on install srtm/map selection screen

### ISSUE THREAD

**Issue by spinza** [southern-wind/wind#43]
Map is no longer loading here:
https://wind-dev.ctwug.za.net/install/?step=mapbounds

**Comment by MDE186** [comment]
It loaded fine when I installed this evening.

**Comment by spinza** [comment]
OK, were you on latest?  I was merging his PRs last night.  @jammin84 changed some map settings.

**Comment by spinza** [comment]
The only other possible explanation I have is that I wasn't running SSL last time I tried install. I can check tonight.

**Comment by MDE186** [comment]
Had the latest before the commits. Will fork them tonight and check again.

**Comment by spinza** [comment]
They are merged to master.  Just update your master.

**Comment by jammin84** [comment]
map changes by me were only link colours. Dont think i did any others?

SSL / maps usually gives a browser debug log entry like this below (fyi. should probably be made into another another issue :stuck_out_tongue_winking_eye: )

```
Mixed Content: The page at 'https://wind-dev.ctwug.za.net/index.php/nodes' was loaded over HTTPS, but requested an insecure image 'http://a.tile.openstreetmap.org/8/142/155.png'. This content should also be served over HTTPS.
```

**Comment by jammin84** [comment]
Fresh install from master here seemed to work ok.

Can this be closed @MDE186

**Comment by MDE186** [comment]
Yes this can be closed.

**Comment by spinza** [comment]
I'm definitely seeing this still.  No map loads on the area selection.

**Comment by spinza** [comment]
I still see this?

**Comment by spinza** [comment]
Nevermind had a browser warning about unsafe scripts that I missed.  Now it works.
