### ISSUE TITLE
some ease of install notes for improvements

### ISSUE THREAD

**Issue by jammin84** [southern-wind/wind#55]
Some Installation steps require unnecessary user interaction at the shell, these are some that I think should be updated.

**install step = perms**
create folders.
- For folders that dont exist (eg ./config ./files/ ./templates/_basic/) have the script create them, rather than complain "they dont have the correct permissions set"

**install step = dbsetup**
The "Install" is only used for new install's, so if the database isn't found, ask to:
- create the database with the previously nominated name.
- Ask if a restricted "wind" user (random generated passwd) with access to only that db is required to be created.

**Comment by jammin84** [comment]
following on from the notes in PR #60 of chicken and egg.

Perhaps the "install" frontend should be changed to a cmd line script as the user executing it would have the necessary privileges to do the required steps.

This would also fix another security concern I have with the config.php file being world writeable by default.

Thoughts?

**Comment by spinza** [comment]
I've seen a number of php open source sites install this way.  I.e. an install page that checks if requirements are met but not able to fix the problems such as folder permissions and/or missing php modules.

I don't see this as a big deal as you need host access in any case and it's a once-off process.  I think some notes on how to install and upgrade is a good idea but other than that I'm happy to leave it unchanged.  Plus example conf files for apache and nginx could also be included in such notes.  That is where I spent most of the time installing this.

Besides the srtm download is more tricky to do on command line.

**Comment by jammin84** [comment]
fair enough. closing.
