### ISSUE TITLE
SOUTHERN-WIND INSTALLATION NON FUNCTIONAL

### ISSUE THREAD

**Issue by SnicketsCPT** [southern-wind/wind#66]
Hi

I Have been trying to get this installation to work and it seems I am now at a loss.
The Base VM with pre-reqs is setup and working (PHP,MySQL & Smarty)
I download a copy of the souther-wind master, and extract it to the www folder.
I create all of the missing folders : 
Templates/_compiled
Templates/_comppiled/basic
files/srtm
files/photos
config
and copy the sample config over as per instructions

After going through the install steps, I delete the install folder and end up with the below WIND homepage result :

![image](https://cloud.githubusercontent.com/assets/12714077/13846712/c39bc196-ec51-11e5-9c52-1b296abb5a67.png)
v

**Comment by spinza** [comment]
Which version of smarty?

**Comment by jammin84** [comment]
Nod @spinza

As per wiki
'Notice that version 2.x is recommended.'

**Comment by spinza** [comment]
To keep an issue open there has to be a bug in software.  We can't tell what's wrong if you don't give details.

**Comment by SnicketsCPT** [comment]
How is it that an issue gets closed within 72 Hours?? I have been away on a long weekend and did not see any e-mail until now, for that I will apologize. 

I am using smarty engine : "Smarty 2.6.23"

**Comment by spinza** [comment]
Web server?  OS?  Web server logs?

**Comment by spinza** [comment]
Also use the latest Smarty 2:
https://github.com/smarty-php/smarty/releases/tag/v2.6.28

**Comment by SnicketsCPT** [comment]
This I have pulled from a webpage inspect

**Comment by SnicketsCPT** [comment]
I will switch on verbose logging and post it here as well.
I Am using Server 2008R2 with IIS and PHP 5.3

**Comment by SnicketsCPT** [comment]
![wind_issue](https://cloud.githubusercontent.com/assets/12714077/13946025/9a16892e-f01a-11e5-97cc-10b271faf0d0.png)

**Comment by SnicketsCPT** [comment]
I Have just upgraded the Smarty engine to the recommended version, still no luck

**Comment by spinza** [comment]
We haven't decided whether we would or would not support Windows but I'd say you are in unchartered waters with Windows.  

Suggest you run Ubuntu 14.04 or similar Debian based OS with Apache (or Nginx).

**Comment by spinza** [comment]
It seems to be looking for the site called templates instead of in the templates folder on your server.  You need to map that to a folder somehow.

**Comment by SnicketsCPT** [comment]
I Have tried this on both Centos and Windows and had the same result, hence why I have logged it ;)

**Comment by spinza** [comment]
I'd suggest a Debian based OS such as Ubuntu.

**Comment by SnicketsCPT** [comment]
I will build a brand new vm again with ubuntu and deploy all of the prereqs as well as wind and post those logs, should I have any further issues.

**Comment by spinza** [comment]
Also share your apache site config when you do.

**Comment by SnicketsCPT** [comment]
Will do thanks

**Comment by jammin84** [comment]
@SnicketsCPT thanks for your feedback and screenshot. By memory I've spoken to you previously on the WiND git. If you've had that working, then this will work on the same config as these variables haven't changed since being forked.

I would have thought CentOS would have worked, my guess is something in your config.php, as these should never be prepended with "http" as seen here, by my 2 examples. Notice it never has a leading http and that it auto adds the sub-directory structure.
![image](https://cloud.githubusercontent.com/assets/6802951/13972480/2fa0c45a-f0d4-11e5-80b2-4106a4500b71.png)

What is the url you are loading being that its trying to load scripts from "http://templates/..." ??

Also, re-check your config.php is pointing to the right smarty file if you changed it.

Can you please tell me what you have configured in config/config.php for the below vars

```
  'site' =>
  array (
    'domain' => 'members.wafreenet.org',
    'url' => 'http://members.wafreenet.org/',
  ),
...
 'templates' =>
  array (
    'path' => './templates/',
    'compiled_path' => './templates/_compiled/',
    'default' => 'basic',
  ),
....
  'smarty' =>
  array (
    'class' => '/blah/Smarty-2.6.28/libs/Smarty.class.php',
  ),
```

@spinza - Some background on this. When loading the "script" url, it uses the $js_dir var.

```
templates/basic/includes/html.tpl:      <script type="text/javascript" src="{$js_dir}/jquery-1.9.1.js"></script>
templates/basic/includes/html.tpl:      <script type="text/javascript" src="{$js_dir}/jquery-ui-1.10.3.custom.min.js"></script>
```

$js_dir is assigned via smarty with surl. 
surl allows it to be smart, in the path being wind is hosted in either the root or a sub-directory.  e.g. mywindhosting.com/ and mywindhosting.com/wind-folder/ will both load without having to change any config.

```
globals/functions.php:  $smarty->assign('js_dir', surl($smarty->template_dir."scripts/javascripts"));
globals/functions.php:  $js_dir = surl($smarty->template_dir . "/scripts/javascripts/");
```

$template_dir assigned via (config.php)

```
globals/common.php:$smarty->template_dir = $vars['templates']['path'].$vars['templates']['default'].'/';
```

**Comment by SnicketsCPT** [comment]
Hi Spinza

Thanks so much for all of the assistance, the wind instance is running now. 

I have one last question : On the browser page title ( the internet tab title) it shows "MY SITE TITLE HERE"  any idea on how to fix this perhaps?

**Comment by SnicketsCPT** [comment]
Also, thanks Jammin84

I never could get the fix to work at that time, I am now assuming that it was my centos vm.

**Comment by spinza** [comment]
@SnicketsCPT 
config/language/english_overwrite.php 
Change it there (and in Greek / Dutch if you want).

**Comment by spinza** [comment]
Thanks @jammin84 .  Any more issues here?  In terms of his logs I thought it was windows logs so assumed it wouldn't work.

**Comment by jammin84** [comment]
@SnicketsCPT can you please share what fixed this as if it was a linux specific / flavour issue I would like to follow it up.

Otherwise we'll close this one out.

**Comment by jammin84** [comment]
@spinza id assumed his screenshot was a browser debug/dev tool log. ie showing elements it couldn't load.

**Comment by SnicketsCPT** [comment]
everything is working very well now :) Thanks once again guys!!

**Comment by SnicketsCPT** [comment]
everything is working very well now :) Thanks once again guys!!

**Comment by spinza** [comment]
Ah I see that could be the chrome console.
