### ISSUE TITLE
Change default plot frequency to 5500 if possible

### ISSUE THREAD

**Issue by spinza** [southern-wind/wind#7]

**Comment by jammin84** [comment]
These would be the places to change.
https://github.com/southern-wind/wind/search?utf8=%E2%9C%93&q=2450

**Comment by spinza** [comment]
Will do.  Happy for me to change this?

**Comment by jammin84** [comment]
yup

**Comment by spinza** [comment]
Closed by #34

**Comment by spinza** [comment]
Closed by #34
