### ISSUE TITLE
Google Earth KML Needs CDATA tags

### ISSUE THREAD

**Issue by spinza** [southern-wind/wind#70]
See https://developers.google.com/kml/documentation/kml_tut#using-the-cdata-element
And this: 
https://github.com/southern-wind/wind/blob/8b895ea17412f883d6e1c876de3c5dc378813363/includes/pages/gearth/gearth_download.php#L65

**Comment by spinza** [comment]
This is in fact a bug. The button below produces invalid KML.  
![image](https://cloud.githubusercontent.com/assets/3501598/15701546/29c71226-27db-11e6-8c0a-243ea14ff709.png)

WiND uses standard HTML inside the the description so we need to wrap the content in CDATA tags as per the example:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <Placemark>
      <name>CDATA example</name>
      <description>
        <![CDATA[
          <h1>CDATA Tags are useful!</h1>
          <p><font color="red">Text is <i>more readable</i> and 
          <b>easier to write</b> when you can avoid using entity 
          references.</font></p>
        ]]>
      </description>
      <Point>
        <coordinates>102.595626,14.996729</coordinates>
      </Point>
    </Placemark>
  </Document>
</kml>
```

I will do it at some point.

**Comment by jammin84** [comment]
oh, I seen it had "htmlspecialchars" in the code. But your right, there's lots that's outside of that so it would be invalid.
